stages:
  - maventry 
  - maventest
  - mavendeploy  
  - androidtry   
  - androidtest   

workflow:
 rules:  
   - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_BRANCH == "main"

maven-build:   
  stage: maventry
  tags:
    - spring_boot
  script:
    - cd Backend
    - mvn package

android-build:
 image:  gjandres/android-ci:latest
 stage: androidtry
 tags:
   - frontend
 before_script:
   - export GRADLE_USER_HOME=`pwd`/.gradle
   - chmod +x ./Frontend/Codenames/gradlew
 script:
   - cd Frontend/Codenames
   - ./gradlew assemble
 artifacts:
   paths:
     - Android_test/app/build/outputs/

maven-test:
  stage: maventest
  tags:
    - spring_boot
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

android-test:
 image:  gjandres/android-ci:latest
 stage: androidtest
 before_script:
   - export GRADLE_USER_HOME=`pwd`/.gradle
   - chmod +x ./Frontend/Codenames/gradlew
 tags:
   - frontend
 script:
   - cd Frontend/Codenames
   - ./gradlew test

auto-deploy:
  stage: mavendeploy  #do make a stage with same name!
  only:
    refs:
      - main
    changes:
      - Backend/**/*
  tags:
   - spring_boot
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
