# Example  .gitlab-ci.yml file
stages:
  - maventry
  - androidtry

autoDeploy:
  stage: maventry  
  tags:
   - springboot_tag
  script:
    - cd Backend/springbootApplication
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
